# Generated by Django 3.0 on 2019-12-07 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('register', '0002_auto_20191207_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='advertise',
            fields=[
                ('adv_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('img', models.ImageField(upload_to='')),
                ('expiree_date', models.DateField()),
                ('field', models.CharField(max_length=400)),
                ('salary', models.IntegerField()),
                ('hours', models.IntegerField()),
                ('Description', models.CharField(max_length=1000)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.employer')),
            ],
        ),
        migrations.CreateModel(
            name='application',
            fields=[
                ('app_id', models.AutoField(primary_key=True, serialize=False)),
                ('adv_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertise.advertise')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='register.employee')),
            ],
        ),
    ]
